CREATE TABLE "quran-verses_quran_verses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quran-verses_quran_verses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"verse" varchar(256),
	"category" varchar,
	"chapterNumber" integer,
	"verseNumber" integer,
	"chapterName" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "verse_idx" ON "quran-verses_quran_verses" USING btree ("verse");